build_ubuntu18.04_3dvg:
	docker build -f Dockerfile_ubuntu18.04_3dvg -t ubuntu18.04_3dvg .
.PHONY: build_ubuntu18.04_3dvg

build_ubuntu18.04_opencv:
	docker build -f Dockerfile_ubuntu18.04_opencv -t ubuntu18.04_opencv .
.PHONY: build_ubuntu18.04_opencv

build_ubuntu18.04_pcl:
	docker build -f Dockerfile_ubuntu18.04_pcl -t ubuntu18.04_pcl .
.PHONY: build_ubuntu18.04_pcl

build_ubuntu18.04_open3d:
	docker build -f Dockerfile_ubuntu18.04_open3d -t ubuntu18.04_open3d .
.PHONY: build_ubuntu18.04_open3d

build_ubuntu18.04_vxl:
	docker build -f Dockerfile_ubuntu18.04_vxl -t ubuntu18.04_vxl .
.PHONY: build_ubuntu18.04_vxl

