FROM ubuntu18.04_miniconda

# Packages
RUN pip install -U pip setuptools

# Basic Python env for scientific computation.
RUN conda update -n base -c defaults conda
RUN conda install -y    \
        ipython         \
        matplotlib      \
        numpy           \
        scipy
RUN conda install -y    \
        h5py            \
        pandas          \
        scikit-learn    \
        scikit-image

#TODO RUN conda install -c plotly plotly=4.1.0
